FROM node:11-alpine

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY . .

RUN yarn 

EXPOSE 3001

ENV NODE_ENV=development

CMD ["npm", "run", "dev"]
