version: '3'

services:
    nodejs:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: nodejs
        restart: unless-stopped
        env_file: .env
        environment:
            - MONGO_HOSTNAME=$MONGO_HOSTNAME
            - MONGO_PORT=$MONGO_PORT
            - MONGO_DB=$MONGO_DB
        ports:
            - "3001:3001"
        networks:
            - app-network
        command: ./wait-for.sh db:27017 -- /usr/src/app/node_modules/.bin/nodemon server.js
    db:
        image: mongo
        container_name: db
        restart: unless-stopped
        env_file: .env        
        volumes:  
            - dbdata:/data/db   
        networks:
            - app-network  
        expose:
            - '27017'
networks:
    app-network:
        driver: bridge

volumes:
    dbdata: